export const menuData = [
    {
        id: 1,
        title: "Strawberry Ice Latte",
        price: 9.0,
        description: "Sirope de fresa con mermelada + leche + hielo.",
        image: "https://theveggieyaya.com/wp-content/uploads/2024/06/iced-strawberry-latte-square-image.jpg",
    },
    {
        id: 2,
        title: "Caramel Ice Latte",
        price: 12.0,
        description:
            "Sirope de caramelo + leche + café + hielo + espuma de leche.",
        image: "https://www.forkinthekitchen.com/wp-content/uploads/2022/09/220629.iced_.latte_.caramel-9182.jpg",
    },
    {
        id: 3,
        title: "Strawberry Ice Latte + Chantilly",
        price: 12.0,
        description:
            "Sirope de fresa con mermelada + leche + hielo + chantilly.",
        image: "https://s-api.qcart.app/images/comoquiero-uploads/images/recipes/originals/6622.jpg?s=716x600&fit=cover&ext=webp",
    },
    {
        id: 4,
        title: "Caramel Ice Latte + Chantilly",
        price: 13.0,
        description:
            "Sirope de caramelo + leche + café + hielo + espuma de leche + chantilly.",
        image: "https://sweetlycakes.com/wp-content/uploads/2023/06/icedcaramellatte-7.jpg",
    },
    {
        id: 5,
        title: "Capuccino Iced",
        price: 11.0,
        description: "Café espresso con leche fría y hielo.",
        image: "https://www.marthastewart.com/thmb/cmDB4xQAGGnJGSf7l_6eC6qi0oc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mld106029_0810_icedcoffee4_vert_0-968b30b35d1e4ec1bb96e7743d397464.jpg",
    },
    {
        id: 6,
        title: "Grange Coffee",
        price: 12.0,
        description: "Café especial con leche y hielo.",
        image: "./cafe-fallback.png",
    },
    {
        id: 7,
        title: "Chocolate caliente",
        price: 6.0,
        description: "Chocolate caliente cremoso.",
        image: "./cafe-fallback.png",
    },
    {
        id: 8,
        title: "Chocolate con chantilly + chispas de chocolate + fudge",
        price: 9.0,
        description:
            "Chocolate caliente con topping de chantilly, chispas de chocolate y fudge.",
        image: "./cafe-fallback.png",
    },
    {
        id: 9,
        title: "Chocolate caliente + marshmello",
        price: 7.0,
        description: "Chocolate caliente con malvaviscos.",
        image: "./cafe-fallback.png",
    },
    {
        id: 10,
        title: "Sub Marino",
        price: 10.0,
        description: "Chocolate especial + leche caliente + espuma de leche.",
        image: "./cafe-fallback.png",
    },
    {
        id: 11,
        title: "Jugo de Papaya",
        price: 6.0,
        description: "Jugo natural de papaya.",
        image: "./cafe-fallback.png",
    },
    {
        id: 12,
        title: "Papaya con leche",
        price: 7.0,
        description: "Jugo de papaya con leche.",
        image: "./cafe-fallback.png",
    },
    {
        id: 13,
        title: "Jugo de Plátano",
        price: 6.0,
        description: "Jugo natural de plátano.",
        image: "./cafe-fallback.png",
    },
    {
        id: 14,
        title: "Plátano con leche",
        price: 7.0,
        description: "Jugo de plátano con leche.",
        image: "./cafe-fallback.png",
    },
    {
        id: 15,
        title: "Jugo de Fresa",
        price: 7.0,
        description: "Jugo natural de fresa.",
        image: "./cafe-fallback.png",
    },
    {
        id: 16,
        title: "Fresa con leche",
        price: 8.0,
        description: "Jugo de fresa con leche.",
        image: "./cafe-fallback.png",
    },
    {
        id: 17,
        title: "Jugo de Mango",
        price: 7.0,
        description: "Jugo natural de mango.",
        image: "./cafe-fallback.png",
    },
    {
        id: 18,
        title: "Mango con leche",
        price: 8.0,
        description: "Jugo de mango con leche.",
        image: "./cafe-fallback.png",
    },
    {
        id: 19,
        title: "Jugo combinado",
        price: 8.0,
        description: "Mezcla de jugos naturales.",
        image: "./cafe-fallback.png",
    },
];
